apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: k8s-3tier-node2
      containers:
        - name: tomcat-container
          image: public.ecr.aws/r2t7n0e1/artifact:jenkins-practice00-6
          imagePullPolicy: Always
